[package]
name = "audio_server"
version = "0.0.1"
edition = "2021"

[lib]


[dependencies]
raalog.workspace = true
toml.workspace = true

tinyaudio = "0.1.1"
rustysynth = "1.2.0"

call_list = { path = "../call_list" }
